name: CI

on:
  pull_request: # trigger on pull requests
    branches:
      - develop
  push:
    branches: # array of glob patterns matching against refs/heads. Optional; defaults to all
      - develop # triggers on pushes that contain changes in develop

jobs:
  Build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
            rust: 1.72.0

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust components
        run: rustup component add rustfmt && rustup component add clippy
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-06-13
          override: true

      - name: Check Rust format
        run: cargo fmt -- --check

      - name: Build aggregator
        run: cargo build --verbose --release

      - name: Test aggregator
        if: github.ref == 'refs/heads/master'
        run: cargo test --all
