name: CI

on:
  pull_request: # trigger on pull requests
  push:
    branches:   # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master        # triggers on pushes that contain changes in master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust components
        run: rustup component add rustfmt && rustup component add clippy
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-01-19
          override: true

      - name: Check Rust format
        run: cargo fmt -- --check

      - name: Build aggregator
        run: cargo build

      - name: Test aggregator
        run: cargo test --all